import DescriptionListWindow from '@/features/work-management/components/DescriptionListWindow.jsx'

const ROWS = [
  '***Vendor not in Netsuite***',
  '***Vendor onboarding not done***',
  'Agency',
  'Agent - Charterer',
  'Agent - Husbandry',
  "Agent - Owner's",
  'CLASSIFICATION SOCIETY',
  'Chandler',
  'Crewing',
  'Hotel',
  'IT Equipment',
  'Insurance',
  'MANUFACTURER',
  'Marine Consultant',
  'Medical Clinic',
  'Other',
  'PORT AGENT',
  'Provision',
  'Regulatory Body',
  'Repairs/ Maintenance',
  'SHIP MANAGER',
  'SHIP OWNER',
  'SUPPLIER',
  'SUPPLIER - SPARES',
  'SUPPLIER - STORES',
  'Service',
  'Service Supplier',
  'Service Supplier - Survey',
  'Service Supplier- LSA/FFA',
  'Service Supplier-Diving',
  'Service Supplier-Elevator',
  'Service Supplier-NDT',
  'Service Supplier-Nav/Com',
  'Service Supplier-TC',
  'Ship Owner/ Manager',
  'Ship to Location',
  'Shipyard',
  'Spares',
  'Stores',
  'Supplier - Charts & Publication',
  'Supplier- Tech Services',
  'Training Institute',
  'Travel Agent',
  'WAREHOUSE',
]

export default function CompanyTypeListWindow(props) {
  return <DescriptionListWindow {...props} title="Company Type List" rows={ROWS} />
}
