import DescriptionListWindow from '@/features/work-management/components/DescriptionListWindow.jsx'

const ROWS = [
  'Commercial - Insurance',
  'Communications - IT',
  'Corporate Policy',
  'Cost Management - Purchasing',
  'Decarbonization, DF Ships',
  'Deck - Bridge/Navigation/GMDSS',
  'Deck - Cargo Operations',
  'Deck - Mooring/Anchoring',
  'Deficiency Management',
  'Documentation - Control/Bulkhead Notice',
  'Emergency Management',
  'Eng - Engineering/Electrical/Maintenance',
  'Eng - Fuel/Lub/Sludge/Bilge Management',
  'Fleet Circular',
  'Fleet Personnel & Training',
  'HSSEQ - Drills & Exercises',
  'HSSEQ - Health/Safety/Permits/Risk Mgmnt',
  'HSSEQ - MARPOL/ Environmental Management',
  'HSSEQ - ORB/GMP/VGP/VECP/SOPEP/NTVRP',
  'HSSEQ - Review/Incidents/Near Miss/Audits',
  'HSSEQ -Security',
  'IHM - SP-618',
  'Management of Change',
  'OH&S ISO 45001',
  'Observations',
  'SP-209 Defeciency Management',
  'Ship Specific Instruction',
  'Various ISM observations',
  'zzISPS Observations',
  'zzSMS- Introduction',
  'zzSP1 Organisation',
  'zzSP1.W1-HSE Committee',
  'zzSP1.W2-Shipboard Mgmt Com',
  'zzSP1.W3-Welfare/Mess Committee',
  'zzSP2 Training',
  'zzSP2.W1-Shipboard Training',
  'zzSP3 - Shipboard Operations',
  'zzSP3.W 1-Health & Safe Working Pract',
  'zzSP3.W 2-Shipboard Security',
  'zzSP3.W 3-CompanyStandingOrd',
  'zzSP3.W 4-Navigation',
  'zzSP3.W 5-Engineering',
  'zzSP3.W 6 Cargo Operations',
  'zzSP3.W 7-Communications',
  'zzSP3.W 8-Personnel Administration',
  'zzSP3.W 9-Purchasing',
  'zzSP3.W10-PSC Inspections, System Audits',
  'zzSP3.W11-Insurance',
  'zzSP3.W12-Ships Specific Instructions',
  'zzSP3.W13 - Filing System',
  'zzSP4.W1-Emergency Preparedness',
  'zzSP4.W2-Environment Protection',
  'zzSP4.W3-Environmental Management',
  'zzSP5 - Deficiences Management',
  'zzSP6 -Shipboard Maintenance',
  'zzSP7.W1-Document Control',
  'zzSP7.W2-Fleet Circulars',
  'zzSP7.W3-Company Forms',
  'zzSP7.W4-Standard Publications',
  'zzShip Security Plan',
]

export default function SmmReferenceListWindow(props) {
  return <DescriptionListWindow {...props} title="SMM Reference List" rows={ROWS} />
}
