import DescriptionListWindow from './DescriptionListWindow.jsx'

const COLUMNS = [
  { key: 'code', label: 'Code', width: '20%' },
  { key: 'desc', label: 'Description' },
]

const ROWS = [
  { code: '0', desc: 'Accounts Receivable', highlight: true },
  { code: '0', desc: 'C - Flag State/Medical' },
  { code: '0', desc: 'C - Leave Pay' },
  { code: '0', desc: 'C - Manning Costs' },
  { code: '0', desc: 'C - Manning Fees' },
  { code: '0', desc: 'C - Overtime - Variable' },
  { code: '0', desc: 'C - Reserve Pay' },
  { code: '0', desc: 'C - Salaries' },
  { code: '0', desc: 'C - Training' },
  { code: '0', desc: 'C - Travel' },
  { code: '0', desc: 'CP - Charterer - Services' },
  { code: '0', desc: 'Drydock - Paint' },
  { code: '0', desc: 'Drydock - Standard' },
  { code: '0', desc: 'EX  - Communications' },
  { code: '0', desc: 'EX - General' },
  { code: '0', desc: 'EX - Management Fees' },
  { code: '0', desc: 'EX - Managers Expenses' },
  { code: '0', desc: 'EX - Port Expenses' },
  { code: '0', desc: 'EX - Survey Fees' },
  { code: '0', desc: 'EX - Vessel Contracts' },
  { code: '0', desc: 'IN - Hull & Machinery' },
  { code: '0', desc: 'IN - Liability' },
  { code: '0', desc: 'IN - Misc Insurance' },
  { code: '0', desc: 'IN - P&I Adv Class 1' },
  { code: '0', desc: 'IN - P&I Adv Class 2' },
  { code: '0', desc: 'IN - P&I Arrears' },
  { code: '0', desc: 'IN - War Risk' },
  { code: '0', desc: 'INS -Mod/New Installation' },
  { code: '11', desc: 'IT' },
  { code: '0', desc: 'LO - Lubricants' },
  { code: '0', desc: 'Local Taxes' },
  { code: '5', desc: 'O - Office' },
  { code: '6', desc: 'O - SCML(Ltd)' },
  { code: '4', desc: 'O - SSML Office' },
  { code: '0', desc: 'OC - Off Charter' },
  { code: '1', desc: 'OEME/UBE-OwnersManages Ex' },
  { code: '0', desc: 'Other Manager Expenses' },
  { code: '0', desc: 'PD - Gas Detection System' },
  { code: '0', desc: 'PD - Predelivery' },
  { code: '0', desc: 'R -  Accommodation' },
  { code: '0', desc: 'R - Auxiliaries Plant' },
  { code: '0', desc: 'R - Cargo Gear' },
  { code: '0', desc: 'R - Damages' },
  { code: '0', desc: 'R - Electrical' },
  { code: '0', desc: 'R - Hull Machinery' },
  { code: '7', desc: 'R - LNG' },
  { code: '0', desc: 'R - ME/AE' },
  { code: '0', desc: 'R - Navigation & Safety' },
  { code: '0', desc: 'R - Pipes & Valves' },
  { code: '0', desc: 'SP - AE' },
  { code: '0', desc: 'SP - Accommodation' },
  { code: '0', desc: 'SP - Auxiliaries Plant' },
  { code: '0', desc: 'SP - Cargo Gear' },
  { code: '0', desc: 'SP - Damages' },
  { code: '0', desc: 'SP - Electrical' },
  { code: '0', desc: 'SP - Freight Expenses' },
  { code: '0', desc: 'SP - Hull Machinery' },
  { code: '8', desc: 'SP - LNG' },
  { code: '0', desc: 'SP - ME' },
  { code: '0', desc: 'SP - ME/AE' },
  { code: '0', desc: 'SP - Navigation & Safety' },
  { code: '0', desc: 'SP - Navigation&Safety' },
  { code: '0', desc: 'SP - Pipes & Valves' },
  { code: '0', desc: 'SP Pipes & Valves' },
  { code: '0', desc: 'ST - Accomm. Stores' },
  { code: '0', desc: 'ST - Chemicals' },
  { code: '0', desc: 'ST - Deck Stores' },
  { code: '0', desc: 'ST - Engine' },
  { code: '0', desc: 'ST - Naut.Charts/Pubs' },
  { code: '0', desc: 'ST - Paint' },
  { code: '0', desc: 'Transfer Order' },
  { code: '0', desc: 'V - V/Bond' },
  { code: '0', desc: 'V - Victualling' },
  { code: '0', desc: 'xDrydock - Accrual' },
  { code: '0', desc: 'xDrydock - Variable' },
]

export default function AccountCategoryListWindow(props) {
  return <DescriptionListWindow {...props} title="Account Category List" columns={COLUMNS} rows={ROWS} />
}
