import DescriptionListWindow from './DescriptionListWindow.jsx'

const ROWS = [
  '2nd Engineer',
  '2nd Officer',
  '3rd Engineer',
  '3rd Officer',
  '4th Engineer',
  '4th Officer',
  '5th Engineer',
  'Accounts - Controller',
  'Accounts - Management',
  'Cadet',
  'Chief Engineer',
  'Chief Officer',
  'Commercial',
  'Commercial - Admin',
  'Crewing  - Accounts',
  'Crewing - AccountsManager',
  'Crewing - Admin',
  'Crewing - Data entry',
  'Crewing - Manager',
  'Crewing - Planner',
  'Crewing - Super',
  'Crewing - Super/Trainer',
  'Crewing-PersonnelOfficer',
  'DATABASE ADMINISTRATOR',
  'Data Manager',
  'Database Administrator',
  'ELT',
  'Electrical Officer',
  'FA - Common',
  'FA - Manager',
  'Finance - Approver',
  'HSEQ -  Manager',
  'HSEQ - Super',
  'IT Administrator',
  'IT Manager',
  'IT Ship Support',
  'Junior Electrical Officer',
  'Junior Engineer',
  'Manning Agent',
  'Manning Agent - Super',
  'Marine - Standard',
  'Master - Payroll',
  'OSS-SIYA',
  'Payroll data migrator',
  'Project Manager',
  'Projects - view',
  'Promotee',
  'Promotion Officer',
  'Public Relations',
  'Publisher',
  'Reporting_ReadOnly',
  'SK - Accounting Manager',
  'SeaSourcing Read Only',
  'Snr Mgr Global Purchasing',
  'Sr Tech - Data specialist',
  'Super User',
  'Tech - Accounts',
  'Tech - Accounts General',
  'Tech - Accounts Lead',
  'Tech - Admin',
  'Tech - Coordinator',
  'Tech - Data Manager',
  'Tech - Data entry',
  'Tech - Data/Admin',
  'Tech - Fleet Director',
  'Tech - Fleet Manager',
  'Tech - Procurement Assist',
  'Tech - Pur Assistant-Repl',
  'Tech - Purchase Manager',
  'Tech - Purchaser',
  'Tech - Purchaser Officer',
  'Tech - Purchaser Sr',
  'Tech - Vessel Manager',
  'Tech-PortDisbursements',
  'Techl - Trg CE/Super',
  'Third Party Access (View)',
  'Trainer',
  'Warehouse',
]

export default function AuthorizationProfileListWindow(props) {
  return <DescriptionListWindow {...props} title="Authorization Profile List" rows={ROWS} />
}
