import DescriptionListWindow from './DescriptionListWindow.jsx'

const ROWS = [
  '01HumanAspectPoorConsider',
  '01PoorAssmtLossExposure',
  '01PoorConstructionMonitor',
  '01PoorStandardSpecsDesign',
  '02PoorIncentives',
  '02PoorInstrsTraining',
  '02PoorLossIdentified',
  '02PoorguidanceDocs',
  '02SettingConflictgGoals',
  '02UnclearConflictReportg',
  '02UnclearconflictRespbty',
  '03InadequateCleaning',
  '03InadequateMonitoring',
  '03InadequateServicing',
  '03Incorrect adjustment',
  '03PartSubstitution',
  '03PoorMaintenancePlanning',
  '03PoorVerifyingWork',
  '03UnawareNS5Schedule',
  '03UnawareOfScheduleChange',
  '03Workload/other pressure',
  '04PoorAssesMaintReqts',
  '04PoorAssessFitForPurpose',
  '04PoorExtnOfServiceLIife',
  '04PoorScheduling of work',
  '05LackOfChangeProcedure',
  '05LackProcedureSupportChg',
  '05PoorProcedureImplment',
  '06NoExistingProcedure',
  '06PoorComOfProcedure',
  '06PoorDevOfProcedure',
  '06PoorProcdureApplication',
  '06PoorUpdatingProcedure',
  '06UnsafeProcedure',
  '07Improper handling',
  '07Improper transporting',
  '07ImproperStorage',
  '07ImproperWasteDisposal',
  '07PoorAcceptance',
  '07PoorID OfHazardItems',
  '07PoorInfRgdgSafetyHealth',
  '07PoorProtectionOfShipmen',
  '07PoorResearchOnEqmt',
  '07PoorSpecifications',
  '07PoorSpecsToSupplier',
  '07Untimely/late delivery',
  '07UsingExpiredOldMaterial',
  '08ImproperDelegation',
  '08PoorActionsCondoned',
  '08PoorEvaluation',
  '08PoorPerformanceFeedback',
  '08PoorPerformanceMonitor',
  '08PoorQualificationForJob',
  '08PoorReinforceOfBehavior',
  '08PoorSupervisoryExample',
  '08PoorSupervisorySkills',
  '09InadequateAvailability',
  '09IncompatibleWorkProcess',
  '09PoorAssessmentOfRisks',
  '09PoorHumanFactorConsider',
  '09PoorMaintenanceRepair',
  '09PoorRemovalOfUnsafeItem',
  '09PoorSalvageReclamation',
  '09PoorSpecsStandard',
  '09UnsafeModification',
  '09Wrong tool for job',
  '10 Lack of coaching',
  '10ImproperPerformanceCond',
  '10Inadequate orientation',
  '10Inadequate practice',
  '10InadequateInitialinstrs',
  '10InadequateUpdateTrg',
  '10InfrequentPerformance',
  '10Lack of experience',
  '10Lack of incentives',
  '10MisunderstoodDirection',
  '10PoorLanguageSkills',
  '10PoorPerformanceFeedback',
  '10ProperPerformanceUnrewa',
  '11AtmosphericPressure',
  '11Blood sugar imbalance',
  '11Confusing Directions',
  '11Constrained movement',
  '11DrugsChemicalImbalance',
  '11Emotional overload',
  '11Excessive frustration',
  '11ExposeToTempExtremes',
  '11ExposureToHealthHazard',
  '11ExtremeConcentrationReq',
  '11ExtremeDecision demands',
  '11FatigueDueLack of rest',
  '11FatigueDuePhysicalTask',
  '11FatigueDueSensoryload',
  '11FatigueDueToHealthIssue',
  '11FatigueMentalTaskLoad',
  '11HighPeerPressure',
  '11Inappropriate aggressio',
  '11Injury or illness',
  '11Meaningless Activities',
  '11OxygenDeficiency/surplu',
  '11PreocupationWithProblem',
  '12EmotionallyDisturb',
  '12Fears&Phobias',
  '12Intelligence',
  '12LowMentalAptitude',
  '12LtdBodyPosition(s)',
  '12MemoryDeficiencies',
  '12MentalIllness',
  '12OtherPermanentDisabilit',
  '12OtherSsensory',
  '12Poor Hearing',
  '12Poor Vision',
  '12PoorAttentionToJob',
  '12PoorBodyMovement',
  '12PoorCoordination',
  '12PoorHeightWeightSize',
  '12PoorJudgment',
  '12PoorRespiratoryCap',
  '12PoorUnderstandg',
  '12SensitivityToTempWx',
  '12SlowReaction',
  '12TemporaryDisability',
  'Management of Change',
  'Observations',
]

export default function CarInternalReferenceTwoListWindow(props) {
  return <DescriptionListWindow {...props} title="CAR Internal Reference Two List" rows={ROWS} />
}
