import DescriptionListWindow from './DescriptionListWindow.jsx'

const ROWS = [
  '*100A1 Container Ship',
  '*A1',
  '*ACCU',
  '*AMS',
  '*IWS',
  '*LMC UMS',
  'BIS',
  'BWM(E(d))',
  'BWM(T)',
  'BoxMax(V,W,L)',
  'CCSA',
  'CM',
  'COMF(C-3, V-3)',
  'CPS',
  'CSSA-R',
  'Clean',
  'Container Carrier',
  'E',
  'E0',
  'ECO(EAL, IBTS, OW, P)',
  'EGCS(Hybrid, Partial)',
  'IHM',
  'IWS',
  'LI',
  'MNS*',
  'NAUT(OC)',
  'NAUTICUS(Newbuilding)',
  'NS*(CNC, EQ C DG)(IWS)(PSCM)MNS*',
  'NS*(CNC, EQ C DG)(PSCM)(IHM) MNS*',
  'NS*(CNC, EQ C DG, 1C)',
  'NS*(CNC, EQ C DG, 1C)(IWS)(PSCM)(IHM) MNS*',
  'NS*(CNC, EQ C DG, 1C)(IWS)(PSCM)(SOX(EGCS))(CSSA) MNS*',
  'NS*(CNC, EQ C DG, 1C)(PS-DA&FA)(IWS)(PSCM)(IHM) MNS*',
  'NS*(CNC, EQ C DG, 1C)(PSCM)(IHM) MNS*',
  'NS*(CNC, EQ C DG, PSPC-WBT, 1C)(PS-DA&FA)(IWS)(PSCM) (IHM) MNS*',
  'NS*(CNC, EQ, C DG, PSPC-WBT, 1C)',
  'PMS(M)',
  'PS-DA&FA',
  'PSCM',
  'SDCL',
  'SH',
  'SHCM',
  'SOX(EGCS)',
  'ShipRight(SDA, FDA plus(25,WW), FDA SPR, WDA2, CM, ACS(B))',
  'TMON',
  'TMON(oil lubricated)',
  'WDA2',
]

export default function MaintenanceNotationListWindow(props) {
  return <DescriptionListWindow {...props} title="Maintenance Notation List" rows={ROWS} />
}
